--- !ditz.rubyforge.org,2008-03-06/project 
name: macroexpand-all
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: macroexpand-all
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.01"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-07-22 05:39:37.136750 Z
    - bowbow99 <bowbow99@gmail.com>
    - created
    - ""
